#define PRODUCT_TYPE    4
#define FLASH_TYPE      6
#define MAJOR_VER       2
#define MINOR_VER       21
#define BUILD_NUM       12
#define BUILD_MONTH     12
#define BUILD_DATE      07
#define BUILD_YEAR      7
#define OEM_CODE        0x0000
